import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#5a4138',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        'outline': '#8e7166',
        'outline-variant': '#e2bfb2',
        'surface-tint': '#a73a00',
        'primary': '#a33900',
        'on-primary': '#ffffff',
        'primary-container': '#cc4900',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#ffb599',
        'secondary': '#855300',
        'on-secondary': '#ffffff',
        'secondary-container': '#fea619',
        'on-secondary-container': '#684000',
        'tertiary': '#006947',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00855b',
        'on-tertiary-container': '#f5fff6',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdbce',
        'primary-fixed-dim': '#ffb599',
        'on-primary-fixed': '#370e00',
        'on-primary-fixed-variant': '#7f2b00',
        'secondary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#ffb95f',
        'on-secondary-fixed': '#2a1700',
        'on-secondary-fixed-variant': '#653e00',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'background': '#faf8ff',
        'on-background': '#131b2e',
        'surface-variant': '#dae2fd',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'margin-lg': '3rem',
        'gutter-md': '1.5rem',
        'space-md': '1rem',
        'margin': '1rem',
        'space-xl': '2rem',
        'gutter': '1rem',
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'margin-md': '1.5rem',
        'gutter-lg': '2rem',
      },
      fontFamily: {
        'sans': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Plus Jakarta Sans', 'sans-serif'],
        'heading': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      boxShadow: {
        'warm': '0 4px 20px -2px rgba(163, 57, 0, 0.08), 0 2px 8px -2px rgba(19, 27, 46, 0.04)',
        'card': '0 2px 8px -2px rgba(234, 88, 12, 0.05), 0 4px 16px -4px rgba(15, 23, 42, 0.06)',
        'tray': '0 12px 32px -4px rgba(15, 23, 42, 0.16), 0 2px 8px 0 rgba(234, 88, 12, 0.08)',
        'bottom-bar': '0 -8px 24px rgba(19, 27, 46, 0.08)',
      },
    },
  },
  plugins: [],
};

export default config;
